# --- Matar los procesos por defecto de Omarchy ---
exec-once = killall awww awww-daemon waybar hyprpaper 2>/dev/null

# --- Inicialización de los servicios hyprpaper ---
exec-once = hyprpaper

# ---  Script de fondos en modo inicialización ---
# Carga el fondo anterior y genera los bordes dinámicos al segundo 1
exec-once = sleep 1 && ~/scripts-system/cambiar_fondo.sh init
