# Change the default Omarchy look'n'feel
source = ~/.cache/wal/colors-hyprland.conf

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling

    # --- Bordes personalizados ---
    col.active_border = $color1 $color1 45deg
    col.inactive_border = rgba(333333aa)
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    # Disable all animations
    enabled = yes

    # La curva de bezier define como se siente el movimiento (aceleración/deceleración)
    bezier = easeOutQuad, 0.25, 0.46, 0.45, 0.94

    # Esto aplica la animación a los movimientos de escritorio (workspaces)
    animation = workspaces, 1, 2, easeOutQuad, slide
    
    animation = windows, 1, 3, easeOutQuad, popin 80%
    animation = fade, 1, 3, easeOutQuad
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}

xwayland {
    force_zero_scaling = true
}

